### ISSUE TITLE
Units of temperature

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/TemperatureMonitoring#10]
If we have a blanket policy of not storing units in databases, because everything is always in SI units, why isn't temperature in Kelvin? (It's in Celsius)

It's tempting to make a branch that converts everything besides display into Kelvin, but I don't see demand beyond my own pedantry.

To address instead what might be the wider question - what is an exemplar way of achieving a database in one unit feeding a dashboard displaying another? In this case the maths is trivial (add / subtract a constant), but often it could be indirectly proportional (Fahrenheit) or logarithms (sound).

- Manipulate the data in Flux / the query 
- Use a Grafana Transformation 
- A fully reusable solution might be an active Analysis Service Module

**Comment by Greg-Hawkridge** [comment]
Celcius is the superior unit - we should convert everyone to the metric system - problem solved. :stuck_out_tongue_closed_eyes:
Everything you've suggested are valid ways of approaching the challenge, but we'll cross the bridge when we get to it.

**Comment by tobyaharris** [comment]
I'd argue Kelvin in superior - many thermodynamic models (esp for for thermistors etc) have to work in absolute temperature and can only convert to C as an afterthought. 

It's a question for the architecture spec to answer, but what is our unit system? Is there a detailed official standard we can adopt for "the metric system" you describe as opposed to SI Units? We don't want to get into the CGS pit. 

https://en.wikipedia.org/wiki/Metric_system#:~:text=The%20current%20international%20standard%20for,kelvin%2C%20mole%2C%20and%20candela.
