### ISSUE TITLE
Changing machine name and threshold in config/toml does not update dashboard

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/TemperatureMonitoring#14]
An issue experienced by @germanterrazas :

## Action 1:
- Assemble solution and clone code. 
- Set unique machine name and threshold in `config.toml`
- `docker compose build` for the first time. 
- `start.sh`
- Navigate to the temperature monitoring dashboard at :3000

### Expected result of action 1:
- The machine name and threshold entered in `config.toml` are pre-populated in the Grafana fields
- Data is immediately visible 

### Observed result of action 1:
As expected? 

## Action 2:
- The solution is stopped with `stop.sh`
- `config.toml` is edited with a new machine name and a different threshold
- the solution is restarted with `start.sh`. 

### Expected result of action 2:
A new dataset is created in influx, is visible in the data explorer at :8086, and in grafana at 3000 the machine (and threshold) fields become dropdowns allowing quick selection of the old or new datasets.

### Observed result of action 2:
The old values persist in the fields. There are no dropdowns. If the new name and threshold are typed exactly, new data becomes visible.

**Comment by Greg-Hawkridge** [comment]
Should have been fixed by #13

**Comment by tobyaharris** [comment]
This was fixed by PR 13, however that was based against an old branch which was binned off when we moved from having 2 persistent branches to 1. It will be recreated - my hesitation has been how long a query to use for detecting machines. For short periods (eg a week as #13 did), data disappears quickly. For long periods, query time becomes a concern.
